package classes;

import enums.ManagerType;
import enums.School;
import enums.UrgencyLevel;
import java.util.*;
import java.util.stream.Collectors;

public class Manager extends Employee implements Comparable<Manager> {
    private static final long serialVersionUID = 1L;

    private ManagerType managerType;
    private School school;

    private List<Course> managedCourses;

    private List<Complaint> receivedComplaints;

    private Map<Student, List<Course>> pendingRegistrations;

    public Manager(String userId, String firstName, String lastName, String email, String password,
                   String department, ManagerType managerType, School school) {
        super(userId, firstName, lastName, email, password, department);
        this.managerType = managerType;
        this.school = school;
        this.managedCourses = new ArrayList<>();
        this.receivedComplaints = new ArrayList<>();
        this.pendingRegistrations = new LinkedHashMap<>();
    }

    public void addCourseForRegistration(Course course) {
        if (!managedCourses.contains(course)) {
            managedCourses.add(course);
            System.out.println("Course added for registration: " + course.getName());
        }
    }

    public void removeCourseFromRegistration(Course course) {
        managedCourses.remove(course);
    }

    public void assignTeacherToCourse(Teacher teacher, Course course, boolean isLecture) {
        if (!managedCourses.contains(course)) {
            System.out.println("Course " + course.getName() + " is not managed by this manager.");
            return;
        }
        if (isLecture) {
            course.addLectureTeacher(teacher);
        } else {
            course.addPracticeTeacher(teacher);
        }
        teacher.addCourse(course);
        System.out.println(teacher.getFullName() + " assigned to " + course.getName()
                + " as " + (isLecture ? "lecture" : "practice") + " instructor.");
    }

    public void unassignTeacherFromCourse(Teacher teacher, Course course) {
        teacher.removeCourse(course);
        course.getLectureTeachers().remove(teacher);
        course.getPracticeTeachers().remove(teacher);
        System.out.println(teacher.getFullName() + " removed from " + course.getName());
    }

    public void submitRegistrationRequest(Student student, Course course) {
        pendingRegistrations
                .computeIfAbsent(student, k -> new ArrayList<>())
                .add(course);
        System.out.println("Registration request queued: " + student.getFullName() + " -> " + course.getName());
    }

    public void approveRegistration(Student student, Course course) {
        List<Course> pending = pendingRegistrations.get(student);
        if (pending == null || !pending.contains(course)) {
            System.out.println("No pending request found for " + student.getFullName() + " in " + course.getName());
            return;
        }
        try {
            student.registerForCourse(course);
            pending.remove(course);
            if (pending.isEmpty()) pendingRegistrations.remove(student);
            System.out.println("Approved: " + student.getFullName() + " registered for " + course.getName());
        } catch (CreditLimitExceededException | TooManyFailsException e) {
            System.out.println("Approval failed: " + e.getMessage());
        }
    }

    public void rejectRegistration(Student student, Course course, String reason) {
        List<Course> pending = pendingRegistrations.get(student);
        if (pending != null) {
            pending.remove(course);
            if (pending.isEmpty()) pendingRegistrations.remove(student);
        }
        System.out.println("Rejected: " + student.getFullName() + " for " + course.getName() + ". Reason: " + reason);
    }

    public Map<Student, List<Course>> getPendingRegistrations() {
        return Collections.unmodifiableMap(pendingRegistrations);
    }


    public void receiveComplaint(Complaint complaint) {
        receivedComplaints.add(complaint);
        System.out.println("Complaint received: " + complaint);
    }

    public List<Complaint> getReceivedComplaints() {
        return Collections.unmodifiableList(receivedComplaints);
    }

    public List<Complaint> getComplaintsByUrgency(UrgencyLevel level) {
        return receivedComplaints.stream()
                .filter(c -> c.getUrgency() == level)
                .collect(Collectors.toList());
    }

    public String generateAcademicReport(List<Student> students) {
        StringBuilder sb = new StringBuilder();
        sb.append("========== ACADEMIC PERFORMANCE REPORT ==========\n");
        sb.append("Generated by: ").append(getFullName()).append(" (").append(managerType).append(")\n");
        sb.append("-------------------------------------------------\n");

        if (students.isEmpty()) {
            sb.append("No students to report.\n");
        } else {
            List<Student> sorted = new ArrayList<>(students);
            Collections.sort(sorted); 

            double totalGPA = 0;
            int passCount = 0;

            for (int i = 0; i < sorted.size(); i++) {
                Student s = sorted.get(i);
                double gpa = s.calculateGPA();
                totalGPA += gpa;
                if (gpa >= 2.0) passCount++;
                sb.append(String.format("%3d. %-30s GPA: %.2f  Fails: %d  Credits: %d%n",
                        i + 1, s.getFullName(), gpa, s.getFailCount(), s.getTotalCredits()));
            }

            double avgGPA = totalGPA / sorted.size();
            sb.append("-------------------------------------------------\n");
            sb.append(String.format("Total students : %d%n", sorted.size()));
            sb.append(String.format("Average GPA    : %.2f%n", avgGPA));
            sb.append(String.format("Passing (GPA≥2): %d (%.1f%%)%n", passCount, 100.0 * passCount / sorted.size()));
        }

        sb.append("=================================================\n");
        return sb.toString();
    }

    public List<Student> getStudentsSortedAlphabetically(List<Student> students) {
        return students.stream()
                .sorted(Comparator.comparing(Student::getLastName).thenComparing(Student::getFirstName))
                .collect(Collectors.toList());
    }

    public List<Student> getStudentsSortedByGPA(List<Student> students) {
        List<Student> sorted = new ArrayList<>(students);
        Collections.sort(sorted);
        return sorted;
    }

    public List<Teacher> getTeachersSortedByRating(List<Teacher> teachers) {
        List<Teacher> sorted = new ArrayList<>(teachers);
        Collections.sort(sorted);
        return sorted;
    }

    public List<Teacher> getTeachersSortedAlphabetically(List<Teacher> teachers) {
        return teachers.stream()
                .sorted(Comparator.comparing(Teacher::getLastName).thenComparing(Teacher::getFirstName))
                .collect(Collectors.toList());
    }

    // ===== Getters / Setters =====

    public ManagerType getManagerType() { return managerType; }
    public void setManagerType(ManagerType managerType) { this.managerType = managerType; }
    public School getSchool() { return school; }
    public void setSchool(School school) { this.school = school; }
    public List<Course> getManagedCourses() { return Collections.unmodifiableList(managedCourses); }

    @Override
    public int compareTo(Manager other) {
        return this.managerType.compareTo(other.managerType);
    }

    @Override
    public String toString() {
        return super.toString() + " | Manager [" + managerType + "] | School: " + school;
    }
}